version: '3.8'

services:
  everspassapi:
    image: everspassapi
    container_name: everspass-webserver
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
      - "7263:443"
    environment:
      - ASPNETCORE_URLS=https://+;http://+
      - ASPNETCORE_HTTPS_PORT=7263
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${ASPNETCORE_Kestrel__Certificates__Default__Password}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      - ASPNETCORE_ENVIRONMENT=Development  # Set your desired environment (Production/Development)

    volumes:
      - ./https:/https:ro

  postgres:
    image: postgres:13
    container_name: everspass-postgres
    environment:
      POSTGRES_DB: everspassdb
      POSTGRES_USER: everspassuser
      POSTGRES_PASSWORD: everspasspw
    ports:
      - "5432:5432"

# Add other services or configurations as needed
